name: logifan
description: Logicbase core libraries for flutter
homepage: https://github.com/masoudcoder/logifan
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  retrofit: ^2.0.1
  intl: ^0.18.1
  device_info: ^2.0.2
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

